### ISSUE TITLE
An error of type E_ERROR on PHP 8.1+

### ISSUE THREAD

**Issue by michaelbeil** [strangerstudios/pmpro-series#96]
**Describe the bug**
A customer ran into an error on PHP 8.1+.

**To Reproduce**
Steps to reproduce the behavior for customer:
1. Set PHP version to PHP 8.1+
2. Activate Paid Memberships Pro and Series Add On. See this error:

```
Error Details
=============
An error of type E_ERROR was caused in line 548 of the file /customers/f/c/c/xxxx/wp-content/plugins/pmpro-series/pmpro-series.php. Error message: Uncaught TypeError: array_merge(): Argument #1 must be of type array, null given in /customers/f/c/c/xxxx.org.uk/httpd.www/wp-content/plugins/pmpro-series/pmpro-series.php:548
Stack trace:
#0 /customers/f/c/c/xxxx/wp-content/plugins/pmpro-series/pmpro-series.php(548): array_merge(NULL, Array)
#1 /customers/f/c/c/xxxx/wp-includes/class-wp-hook.php(310): pmpros_plugin_action_links(Array)
#2 /customers/f/c/c/xxxx/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array)
#3 /customers/f/c/c/xxxx/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-sync/src/modules/class-callables.php(384): apply_filters(‘plugin_action_l…’, Array, ‘pmpro-series/pm…’, NULL, ‘all’)
#4 /customers/f/c/c/xxxx/wp-includes/class-wp-hook.php(308): Automattic\Jetpack\Sync\Modules\Callables->set_plugin_action_links(Object(WP_Screen))
#5 /customers/f/c/c/xxxx/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#6 /customers/f/c/c/xxxx/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /customers/f/c/c/xxxx/wp-admin/includes/class-wp-screen.php(424): do_action(‘current_screen’, Object(WP_Screen))
#8 /customers/f/c/c/xxxx/wp-admin/includes/screen.php(243): WP_Screen->set_current_screen()
#9 /customers/f/c/c/xxxx/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-sync/src/class-sender.php(505): set_current_screen(‘sync’)
#10 /customers/f/c/c/xxxx/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-sync/src/class-sender.php(601): Automattic\Jetpack\Sync\Sender->get_items_to_send(Object(Automattic\Jetpack\Sync\Queue_Buffer), true)
#11 /customers/f/c/c/xxxx/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-sync/src/class-sender.php(462): Automattic\Jetpack\Sync\Sender->do_sync_for_queue(Object(Automattic\Jetpack\Sync\Queue))
#12 /customers/f/c/c/xxxx/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-sync/src/class-sender.php(341): Automattic\Jetpack\Sync\Sender->do_sync_and_set_delays(Object(Automattic\Jetpack\Sync\Queue))
#13 /customers/f/c/c/xxxx/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-sync/src/class-actions.php(704): Automattic\Jetpack\Sync\Sender->do_sync()
#14 /customers/f/c/c/xxxx/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-sync/src/class-actions.php(644): Automattic\Jetpack\Sync\Actions::do_cron_sync_by_type(‘sync’)
#15 /customers/f/c/c/xxxx/wp-includes/class-wp-hook.php(308): Automattic\Jetpack\Sync\Actions::do_cron_sync()
#16 /customers/f/c/c/xxxx/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(”, Array)
#17 /customers/f/c/c/xxxx/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#18 /customers/f/c/c/xxxx/wp-cron.php(188): do_action_ref_array(‘jetpack_sync_cr…’, Array)
#19 {main}
thrown
```
There should not be an error.

**Isolating the problem:**
- [x] Deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro 2.9.12, and Series Add On .5 is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).

This came up in ticket 481014 on PHP 8.1.16 and 8.0.28. I am not seeing any error with PHP 8.0.22. 

**WordPress Environment**
<details> 
Paid Memberships Pro 2.10.1, Series Add On .5, WordPress 6.1.1, PHP 8.1.16
</details>

**Comment by michaelbeil** [comment]
Another customer (ticket 484997) ran into this:
>we saw a bug appear in a log that we do not understand

I mentioned that this will be looked into in the future, and I asked if they can downgrade, or turn off [WP_DEBUG_DISPLAY](https://www.paidmembershipspro.com/how-to-enable-debugging-on-you-your-wordpress-site/).
